# Generated by Django 4.2.4 on 2023-08-02 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.UUIDField(default=uuid.UUID('a39636f6-0912-4a43-ba3a-8368ebd72106')),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
