# Generated by Django 4.2.4 on 2023-08-02 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_id_alter_invoice_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.UUIDField(default=uuid.UUID('e8d413b2-c36d-4315-ae33-d31e3196d9b7')),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='details', to='core.invoice'),
        ),
    ]
