# Generated by Django 4.2.4 on 2023-08-02 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_invoice_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.UUIDField(default=uuid.UUID('ff8e840e-3ba9-496b-9af0-c855e69ac72a')),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
